# Terraform S3 Backend Configuration
# Auto-generated by setup-backend-auto.sh

terraform {
  backend "s3" {
    bucket         = "bharatvani-terraform-state-797882812707"
    key            = "bharatvani/terraform.tfstate"
    region         = "ap-south-1"
    dynamodb_table = "bharatvani-terraform-locks"
    encrypt        = true
  }
}
