#!/bin/bash
set -e

echo "=========================================="
echo "Automated Terraform S3 Backend Setup"
echo "=========================================="
echo ""

# Get AWS account ID
ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
if [ -z "$ACCOUNT_ID" ]; then
    echo "❌ Error: Unable to get AWS account ID. Please configure AWS credentials first."
    exit 1
fi

echo "✓ AWS Account ID: $ACCOUNT_ID"
echo ""

# Define bucket and table names
BUCKET_NAME="bharatvani-terraform-state-${ACCOUNT_ID}"
TABLE_NAME="bharatvani-terraform-locks"
REGION="ap-south-1"

# Create S3 bucket
echo "Creating S3 bucket..."
if aws s3 mb s3://${BUCKET_NAME} --region ${REGION} 2>/dev/null; then
    echo "✓ S3 bucket created: ${BUCKET_NAME}"
else
    echo "⚠ S3 bucket already exists. Continuing..."
fi

# Enable versioning
aws s3api put-bucket-versioning \
    --bucket ${BUCKET_NAME} \
    --versioning-configuration Status=Enabled \
    --region ${REGION}
echo "✓ Versioning enabled"

# Enable encryption
aws s3api put-bucket-encryption \
    --bucket ${BUCKET_NAME} \
    --server-side-encryption-configuration '{
        "Rules": [{
            "ApplyServerSideEncryptionByDefault": {
                "SSEAlgorithm": "AES256"
            }
        }]
    }' \
    --region ${REGION}
echo "✓ Encryption enabled"

# Block public access
aws s3api put-public-access-block \
    --bucket ${BUCKET_NAME} \
    --public-access-block-configuration \
        "BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true" \
    --region ${REGION}
echo "✓ Public access blocked"

# Create DynamoDB table
echo "Creating DynamoDB table..."
if aws dynamodb create-table \
    --table-name ${TABLE_NAME} \
    --attribute-definitions AttributeName=LockID,AttributeType=S \
    --key-schema AttributeName=LockID,KeyType=HASH \
    --billing-mode PAY_PER_REQUEST \
    --region ${REGION} \
    --tags Key=Project,Value=BharatVani Key=Purpose,Value=TerraformStateLocking \
    >/dev/null 2>&1; then
    echo "✓ DynamoDB table created: ${TABLE_NAME}"
    aws dynamodb wait table-exists --table-name ${TABLE_NAME} --region ${REGION}
    echo "✓ Table is active"
else
    echo "⚠ DynamoDB table already exists. Continuing..."
fi

# Update backend.tf automatically
echo ""
echo "Updating backend.tf with your account ID..."
cat > backend.tf << EOF
# Terraform S3 Backend Configuration
# Auto-generated by setup-backend-auto.sh

terraform {
  backend "s3" {
    bucket         = "${BUCKET_NAME}"
    key            = "bharatvani/terraform.tfstate"
    region         = "${REGION}"
    dynamodb_table = "${TABLE_NAME}"
    encrypt        = true
  }
}
EOF

echo "✓ backend.tf updated"
echo ""
echo "=========================================="
echo "✓ Setup complete!"
echo "=========================================="
echo ""
echo "Backend configuration:"
echo "  Bucket: ${BUCKET_NAME}"
echo "  Table: ${TABLE_NAME}"
echo "  Region: ${REGION}"
echo ""
echo "Next step:"
echo "  Run: terraform init -migrate-state"
echo ""
